### ISSUE TITLE
mapping values are not allowed in this context

### ISSUE THREAD

**Issue by Sapp00** [budimanjojo/talhelper#653] opened 2024-10-14 11:40 UTC
Hi,

I am facing the error "mapping values are not allowed in this context" when parsing my talconfig. 

The respective block is the following:
```
---
clusterName: ${clusterEndpointName}
talosVersion: v1.7.6
kubernetesVersion: v1.30.3
# endpoint: https://${clusterEndpointName}.${domainName}:6443
endpoint: https://10.10.10.11:6443
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.242.0.0/16
cniConfig:
  name: none
allowSchedulingOnControlPlanes: false

nodes:
  - hostname: k8s-control01.${domainName}
    ipAddress: 10.10.10.11
    installDisk: /dev/sda
    controlPlane: true
    nameservers:
      - ${nameServer}
      - 1.1.1.1
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vip:
          ip: 10.10.10.10
  - hostname: k8s-control02.${domainName}
    ipAddress: 10.10.10.12
    installDisk: /dev/sda
    controlPlane: true
    nameservers:
      - ${nameServer} # <--- line 36
      - 1.1.1.1
    networkInterfaces:
      - interface: eth0
        dhcp: true

controlplane:
  patches:
    [....]
    - |-
      - op: replace
        path: /cluster/etcd/ca
        value:
          crt: ${etcdCACert}
          key: ${etcdCAKey}
    [....]
```

I have no clue where this error is coming from, before reworking my configs, it was "working". Working means, that it did not throw an error, but somehow the configs were just the basic configs without my customization.

**Comment by Sapp00** [comment] 2024-10-14 23:11
I could track it down and the error message appears because of malformed patches, which is not really intuitive.

This is the error causing patch:
```
    - |-
      - op: replace
        path: /cluster/etcd/ca
        value:
          crt: ${etcdCACert}
          key: ${etcdCAKey}
```
any idea what is wrong with it?

**Comment by budimanjojo** [comment] 2024-10-15 03:21
Thanks for the report!

I just tried the `talconfig.yaml` you provided above (with the ${} replaced) and `talhelper genconfig` ran fine. I think the error message is you have wrong kind of value in your `talenv.yaml` file? Make sure they are in `key: value` format, for example yours should look somethine like this:
```yaml
clusterEndpointName: clustername
domainName: domainname
nameServer: 1.2.3.4
etcdCACert: LS0tLS1CRUdblbalbalballaba
etcdCAKey: LS0tLS1CRUdblbalbalballaba
```

Another one is there's no `controlplane` key, it should be `controlPlane`.

**Comment by Sapp00** [comment] 2024-10-16 21:20
The controlplane is a typo, but just occured when I truncated some info.

My talenv.sops.yaml is actually in the right format:

```
domainName: cluster.local
nameServer: 10.10.10.1
clusterEndpointName: home
clusterEndpointIP: 10.10.10.10
aggregatorCert: 123456
aggregatorKey: 123456
clusterCACert: 123456
clusterCAKey: 59hadfa9
etcdCACert: afsidiisafjafjidaf
etcdCAKey: afiadsfiansfaindfaasfiodsafo
machineCACert: asfjoiadsfijdsfoia
machineCAKey: 2orijaiusdfinsafadsf
serviceAccountKey: ab123
secretboxEncryptionSecret: aaijdfaf
clusterSecret: sdnidasgindgd
clusterToken: adjifaiugdu
machineToken: uhefiasdiufs
```

**Comment by budimanjojo** [comment] 2024-10-17 05:19
I found a lot of problem with your patches:
- `path: /cluster/controllermanager/extraArgs` should be `path: /cluster/controllerManager/extraArgs`
- `path: /cluster/apiserver/extraArgs` should be `path: /cluster/apiServer/extraArgs` and please remove `admissionControl: []` from the value
- You didn't put `value:` after the line `path: /cluster/ca`

I also suggest you to use `talsecret.sops.yaml` to store those secrets instead of putting so many patches. Not sure why you prefer using patches. Read this documentation for more information: https://budimanjojo.github.io/talhelper/latest/getting-started/#you-already-have-a-talos-cluster-running

**Comment by budimanjojo** [comment] 2024-10-18 02:03
Closing this now as it seems like not a bug.

**Closed by budimanjojo** 2024-10-18 02:03 UTC
