### ISSUE TITLE
talhelper parsing issue for extraManifests yaml starting with ---

### ISSUE THREAD

**Issue by AjayKumar4** [budimanjojo/talhelper#497] opened 2024-06-04 00:08 UTC
NodeConfigs:
    extraManifests:
        - tailscale.yaml
        
  
  tailscale.yaml
 ```
 ---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
  - TS_AUTHKEY="<tailscale_key>"
 ```
 
 error message : missing kind from yaml
 talhelper version: 1.7.4

**Comment by budimanjojo** [comment] 2024-06-04 04:09
Thanks for the report @AjayKumar4!

I just tried this and it works fine here. I think the `talconfig.yaml` you provided is wrong. It should be like this:
```yaml
nodes:
  - extraManifests:
      - tailscale.yaml
```

The `nodeConfigs` key is inline for `nodes` and `controlPlane` and `worker` struct. So you use it like this:
```yaml
nodes:
  - <everythingInsideNodeConfigsStruct>:
worker:
  <everythingInsideNodeConfigsStruct>:
controlPlane:
  <everythingInsideNodeConfigsStruct>:
```

The only downside of having `---` in the file is that the generated manifest will have double document delimiter, but it should work just fine as long as the provided file is a valid yaml formatted document.

**Comment by budimanjojo** [comment] 2024-06-04 04:30
Wait, you're using `talhelper` v1.7.4 which is VERY outdated. Please update it first.

**Comment by budimanjojo** [comment] 2024-06-04 06:38
Ah, so the issue is `talosctl` doesn't like the double document delimiter. This should be easily fixed with removing the `---` when it exists, but the code will be very ugly. I see what I can do.

**Comment by AjayKumar4** [comment] 2024-06-04 06:43
yup, this function need some upgrade 
https://github.com/budimanjojo/talhelper/blob/32f7d1b6e241999e5adfb01457e5d3e1f1b3fb2b/pkg/generate/config.go#L164

**Comment by budimanjojo** [comment] 2024-06-04 07:08
Created the PR for the fix, but currently I'm still working on fixing the go module issue so this will be released alongside `v3.0.0`. For now you can remove the `---` in `tailscale.yaml` file for the workaround. Thank you for reporting this!

**Comment by AjayKumar4** [comment] 2024-06-04 07:11
instead of trim you can do check in
https://github.com/budimanjojo/talhelper/blob/32f7d1b6e241999e5adfb01457e5d3e1f1b3fb2b/pkg/talos/networkconfig.go#L80
```
// CombineYamlBytes prepends and returns `---\n` before `input`, unless the input already starts with `---\n`.
func CombineYamlBytes(input [][]byte) []byte {
	delimiter := []byte("---\n")
	var result []byte
	for k := range input {
		if !bytes.HasPrefix(input[k], delimiter) {
			result = append(result, delimiter...)
		}
		result = append(result, input[k]...)
	}
	return result
}
```

**Comment by budimanjojo** [comment] 2024-06-04 07:13
Oh yeah good catch, putting it there makes more sense. Thank you! I'll update the commit

**Closed** 2024-06-04 09:24 UTC
